name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.10.0"
          modules: qtmultimedia

      - name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Configure
        run: cmake --preset vcpkg -DCMAKE_PREFIX_PATH="${Qt6_DIR}/../../.."

      - name: Build
        run: cmake --build --preset vcpkg --parallel
